export const REGISTRATION = {
	UPDATE_CODE: 'UPDATE_CODE',
	REGISTER: 'REGISTER',
	SET_ERROR: 'SET_ERROR',
	SET_REGISTERED: 'SET_REGISTERED',
};

export const MAP_CONTROLLER = {
	DATASET: 'DATASET',
	IS_PLAYING: 'IS_PLAYING',
	SET_REGION: 'SET_REGION',
	SET_YEAR: 'SET_YEAR',
	STOP_ENABLED: 'STOP_ENABLED',
};
