export const REGISTRATION = {
	UPDATE_CODE: 'UPDATE_CODE',
	REGISTER: 'REGISTER',
	SET_REGISTERED: 'SET_REGISTERED',
};

export const MAP_CONTROLLER = {
	IS_PLAYING: 'IS_PLAYING',
	SET_YEAR: 'SET_YEAR',
	STOP_ENABLED: 'STOP_ENABLED',
};
